import Head from 'next/head';
import { GetStaticProps } from 'next';
import { useTranslation } from 'next-i18next';
import { Header } from '../components/Header';
import { LoadTranslation } from '../utils/translation';

import styles from "../styles/datime.module.css"

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await LoadTranslation(locale!, ["datime"])),
    },
  };
}

export default function Datime() {
  const { t } = useTranslation("datime");

  return (
    <div>
      <Head>
        <title>{t(["title"])}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <Header />
        <div className={styles.main}>
          <h2 className={styles.title}>
            {t(["title"])}
          </h2>

          <button className={styles.button}
            type="button"
          >
            {t(["clickText"])}
          </button>
        </div>
      </div>
    </div>
  )
}
