import Head from 'next/head';
import Link from 'next/link';
import { Header } from '../components/Header';
import { GetStaticProps } from 'next';
import { useTranslation } from 'next-i18next';
import { LoadTranslation } from '../utils/translation';
import { useState } from 'react';

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  const translation = await LoadTranslation(locale!, ["home"])
  // console.log(translation);
  return {
    props: {
      ...(translation),
    },
  };
}

export default function Home() {
  const { t } = useTranslation("home");
  const [messagesCounter, setMessagesCounter] = useState(0);

  return (
    <div>
      <Head>
        <title>{t(["title"])}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <h1>{t("title")}</h1>
      <h3>{t("description")}</h3>

      <p>
        {t("unreadMessages", {
          count: messagesCounter,
        })}
      </p>

      <button onClick={() => {setMessagesCounter(prev => prev + 1)}}>+</button>
      <button onClick={() => {setMessagesCounter(prev => prev - 1)}}>-</button>

      <Link href="/contact">
        <span>{t("contactLink")}</span>
      </Link>
      <br />
      <Link href="/datime">
        <span>{t("datimeLink")}</span>
      </Link>
    </div>
  )
}
